### ISSUE TITLE
Add a song

### ISSUE THREAD

**Issue by Ghost2000gmd** [NAEL2XD/Songs-to-chart-Requests#10]
### Link to the song.

https://www.youtube.com/watch?v=WbPnlgJ-bs0

### If you know the bpm of the song you've wanna request, input here! Make sure it's in numbers.

522

### Have any extra sprites? Send them here!

https://drive.google.com/drive/folders/1--853Cgqc5Jmxub4MHnVVsTW7L0Fn6CT

**Comment by NAEL2XD** [comment]
this song sucks, even tho it is 2 years old
