### ISSUE TITLE
miragist

### ISSUE THREAD

**Issue by trademarkman** [NAEL2XD/Songs-to-chart-Requests#11]
### Link to the song.

https://www.youtube.com/watch?v=2q4ygmoIViY

### If you know the bpm of the song you've wanna request, input here! Make sure it's in numbers.

168 (spam parts bpm are 6.72.e6)

### Have any extra sprites? Send them here!

i dont have them

**Comment by trademarkman** [comment]
blud can just make illusory by itself 😭

**Comment by NAEL2XD** [comment]
no extra sprite? guess i'll beg for justamz :trollface:

**Comment by NAEL2XD** [comment]
k done

**Comment by trademarkman** [comment]
i do have sprites just ask me for it on discord but it will be trash tho
toast0431
