### ISSUE TITLE
PHYSICALLY UNBOUND aka Theoretically Possible Song 2 (CREDIT JJ1982 FOR SONG AND ME FOR OC)

### ISSUE THREAD

**Issue by TofpFL** [NAEL2XD/Songs-to-chart-Requests#12]
### Link to the song.

https://www.youtube.com/watch?v=R863X4gVZPA

### If you know the bpm of the song you've wanna request, input here! Make sure it's in numbers.

750 for 96PPQ Manipulation, 1000 BPM Base song

### Have any extra sprites? Send them here!

https://drive.google.com/drive/folders/1_HUu6qbUa1VOV_8J2TFSmDNWyVL1uMfc

**Comment by TofpFL** [comment]
btw oc name is DATA_ERROR or Montreal88 because backstory: DATA_ERROR is a Render Issue of Montreal88.wav

**Comment by NAEL2XD** [comment]
that note pattern was so confusing that i made it as a rule, i can try to use sniff if you have access to flps

**Comment by NAEL2XD** [comment]
closed because confusing patterns

**Comment by TofpFL** [comment]
luckily i already added my sprites into the game now its just time for my PC to survive XD

**Comment by TofpFL** [comment]
I added FLM in zip and Midi into drive

**Comment by TofpFL** [comment]
https://drive.google.com/drive/folders/1Cz2YfZjbzZvnpQPyWJ8PgE3Q5whTr4Id

**Comment by TofpFL** [comment]
ᎵᏲᎽᎦᎥᏟᎯႱႱᎽ Ꮼ𐒐Ᏸ𐒀Ꮼ𐒐Ꮄ video title name
