### ISSUE TITLE
Ŧ๏гє๏г๔คเภє๔

### ISSUE THREAD

**Issue by trademarkman** [NAEL2XD/Songs-to-chart-Requests#13]
### Link to the song.

https://www.youtube.com/watch?v=y3-L1K3sWOs

### If you know the bpm of the song you've wanna request, input here! Make sure it's in numbers.

250

### Have any extra sprites? Send them here!

https://drive.google.com/drive/folders/1Ivurd_zY-FDygwYjYhr6KoYxxWHCMAfY

**Comment by NAEL2XD** [comment]
Wowza!! done
