### ISSUE TITLE
rechart this

### ISSUE THREAD

**Issue by nikitabaev71** [NAEL2XD/Songs-to-chart-Requests#14]
### Link to the song.

https://www.youtube.com/watch?v=SbMA-2u4JRg

### BPM

116

### Extra Sprites

its just black screen no extra sprites needed :)

**Comment by nikitabaev71** [comment]
also forgot to say that its auricular death 5 by iamcyklus. on discord

**Comment by NAEL2XD** [comment]
that chart is fine, but holy shit there's no way i'm allowing this because it's extremely loud
