### ISSUE TITLE
🅐︎🅖︎🅞︎🅝︎🅘︎🅩︎🅔︎🅓︎ 🅗︎🅔︎🅐︎🅡︎🅣︎🅑︎🅡︎🅔︎🅐︎🅚︎

### ISSUE THREAD

**Issue by MrolYT** [NAEL2XD/Songs-to-chart-Requests#15]
### Link to the song.

https://youtu.be/79xB8CwKAFE?si=-PBfcZ1Y779wsHkU

### BPM

180, 510×

### Extra Sprites

I think @BobbbyOffical

**Comment by MrolYT** [comment]
My username is @TotallyMrol on YouTube

**Comment by NAEL2XD** [comment]
sorry but i won't add
