### ISSUE TITLE
ղѻçէմɾղҽ - Vs. Bambi Fantrack its called nocturne without minecraft language lol i made xml and json for it

### ISSUE THREAD

**Issue by trademarkman** [NAEL2XD/Songs-to-chart-Requests#18]
### Link to the song.

https://www.youtube.com/watch?v=Bdp1Fz7tK8g

### BPM

252

### Extra Sprites
i made xml and json lol

https://discord.com/channels/1036051546284249139/1244195757117014086

**Comment by NAEL2XD** [comment]
delays, *ugh*
