### ISSUE TITLE
Disruphobia v3

### ISSUE THREAD

**Issue by MishaFNF** [NAEL2XD/Songs-to-chart-Requests#19]
### Link to the song.

https://youtu.be/qEXAjkVHkUo?si=C_MaUmnyIRfr2DYX

### BPM

260

### Extra Sprites

https://drive.google.com/file/d/16udHZpPyV_qzNflzuZ8-nFGnNu53Ic1H/view?usp=drivesdk

**Comment by NAEL2XD** [comment]
no sorry
