### ISSUE TITLE
HELP ME MICKEY by datonerylsguyfrfr

### ISSUE THREAD

**Issue by newfuckingplayer** [NAEL2XD/Songs-to-chart-Requests#2]
### Insert the Song name in the title, then you can paste the link here, optional.

https://www.youtube.com/watch?v=JjqQ6fU53jA
anyways bpm is 200 in game 
![download (9)](https://github.com/NAEL2XD/Songs-to-chart-Requests/assets/118622687/763986bc-b58d-40fc-9bad-b3f8575dcf0b)

**Comment by NAEL2XD** [comment]
Ok looking into the song

**Comment by NAEL2XD** [comment]
Done.
