### ISSUE TITLE
Sonorous

### ISSUE THREAD

**Issue by CoolArsenCreatingMods** [NAEL2XD/Songs-to-chart-Requests#22]
### Link to the song.

https://youtu.be/D37c4fOcD90?si=G8T482NNFKaqOPNn

### BPM

522

### Extra Sprites

Bambi

**Comment by NAEL2XD** [comment]
i charted 3 times, even in my [video](https://www.youtube.com/watch?v=_jWIDyvjQuU) and yet you want me to rechart again?

**Comment by trademarkman** [comment]
lol
