### ISSUE TITLE
ＡＮＹＰＡＲＸＩＡ (ᴷᴬᵀᴴᴬᴿᴵᶻᴼ 2) - Bambi Fantrack (EXTRATONE, LOUD)

### ISSUE THREAD

**Issue by BambiGaming2022** [NAEL2XD/Songs-to-chart-Requests#23]
### Link to the song.

https://www.youtube.com/watch?v=9pL88oFwN0U

### BPM

200

### Extra Sprites

lazy ass

**Comment by NAEL2XD** [comment]
and it's done
