### ISSUE TITLE
Add a song

### ISSUE THREAD

**Issue by Ghost2000gmd** [NAEL2XD/Songs-to-chart-Requests#25]
### Link to the song.

https://www.youtube.com/watch?v=crTy1-WV0nE&t=52s

### BPM

it doesnt say

**Comment by NAEL2XD** [comment]
1. invalid title
2. did you really missed this?
![image](https://github.com/NAEL2XD/Songs-to-chart-Requests/assets/108278470/14349e35-339b-4804-b716-c23852666f02)

**Comment by Ghost2000gmd** [comment]
missed what?

**Comment by NAEL2XD** [comment]
Ok there's no way your iq is above 80

**Comment by Ghost2000gmd** [comment]
The bpm is 118
\
