### ISSUE TITLE
sharpness but spam

### ISSUE THREAD

**Issue by Dimarar** [NAEL2XD/Songs-to-chart-Requests#26]
### Link to the song.

https://youtu.be/0V6nxffu-EI?si=0HGUxUm83N0dvMdP

### BPM

156

### Extra Sprites

sorry but i dont have it :(

**Comment by NAEL2XD** [comment]
bpm is wrong

**Comment by Dimarar** [comment]
> bpm is wrong

Uhhhhh.... Im using this bpm for my mod. By my opinion is normal

**Comment by Dimarar** [comment]
+ in original mod sharpness is have wrong bpm (its slow)

**Comment by NAEL2XD** [comment]
> * in original mod sharpness is have wrong bpm (its slow)

you coulda used 
![image](https://github.com/user-attachments/assets/7e7e2761-67ef-48b6-b4b6-e5d7ca77f3d7)
261

+ i included the link where if the bpm ison found then you have to do it

**Comment by NAEL2XD** [comment]
anyways it's done
