### ISSUE TITLE
floccinaucinihilipilificatiophobia

### ISSUE THREAD

**Issue by emsoftworks** [NAEL2XD/Songs-to-chart-Requests#28]
### Link to the song.

https://www.youtube.com/watch?v=5k6PIQUAITc&t=84s

### BPM

255

**Comment by NAEL2XD** [comment]
i seen lots of this charted, but i'm gonna be one of em

**Comment by emsoftworks** [comment]
EPICC

**Comment by emsoftworks** [comment]
heres flp

https://drive.google.com/file/d/1Fbi3hp3LkNlwaR7HYt2bTGB9u_qCKSWp/view

**Comment by NAEL2XD** [comment]
WAIT WAIT WAIT this is loud as fuck on hypertone, ain't charting it

**Comment by cyklusiguess** [comment]
this overrated ass song
