### ISSUE TITLE
Realisticful (NULLIFIED) - Vs Nuggs UST

### ISSUE THREAD

**Issue by YassinIzakane** [NAEL2XD/Songs-to-chart-Requests#3]
### Insert the Song name in the title, then you can paste the link here, optional.

https://www.youtube.com/watch?v=omd1ydDa2Rw&list=PLS0y6kgcvMp01FANklaubTvYfdP1E37Ey&index=4

song info:
Name: Realisticful (NULLIFIED)
UST/OST: VS Nuggs
Duration: 5:41 minutes (341 seconds)
Base BPM: 420

**Comment by NAEL2XD** [comment]
mfw recharted in osu

ok i'll do it this time it's an actual banger

**Comment by NAEL2XD** [comment]
nvm

**Comment by YassinIzakane** [comment]
> mfw recharted in osu
> 
> ok i'll do it this time it's an actual banger

since when it was charted in osu

**Comment by NAEL2XD** [comment]
a very long time ago
