### ISSUE TITLE
Evil Smoke (encore) (the song is a joke just so you know)

### ISSUE THREAD

**Issue by BanserReal** [NAEL2XD/Songs-to-chart-Requests#31]
### Link to the song.

https://www.youtube.com/watch?v=peLiuKKwVsk

### BPM

158 (intro) --> 168 (after weedbi.exe finishes laughing)

### Extra Sprites

https://drive.google.com/drive/folders/1n3gio9xrklg7Te_fiqxmkzuW2v7w3-0w?usp=sharing

**Comment by NAEL2XD** [comment]
forgot that it's done azsfrhfoshgdofm
