### ISSUE TITLE
Vs. Chah'weh - Trepidatious

### ISSUE THREAD

**Issue by Ghost2000gmd** [NAEL2XD/Songs-to-chart-Requests#32]
### Link to the song.

https://www.youtube.com/watch?v=sTocR0-T8a0

### BPM

531 - 50976 - 531 - 50976 - 531

### Extra Sprites

https://drive.google.com/file/d/1AIByGhC7zHbc43kFZd2dNtuzxX0_U0oP/view its all assets in a rar

**Comment by NAEL2XD** [comment]
i'm switching to trepidatious, much better than annakannazoozoo
