### ISSUE TITLE
Колапс стварности, за све си ти крив (the fundamental parts of life and destruction 2) chart request

### ISSUE THREAD

**Issue by leaked123** [NAEL2XD/Songs-to-chart-Requests#38]
### Link to the song.

https://www.youtube.com/watch?v=EUT3FCuf5aY

### BPM

110

### Extra Sprites

all i got sorry bro, by @HomieNukeMarkRealNoFake on YouTube: https://drive.google.com/file/d/1bW2u1sFIpVqnH2aMP1dprB6L9arEbrEx/view?usp=sharing

**Comment by NAEL2XD** [comment]
Rule 2
