### ISSUE TITLE
Саставни део живота и уништења chart request

### ISSUE THREAD

**Issue by leaked123** [NAEL2XD/Songs-to-chart-Requests#39]
### Link to the song.

https://www.youtube.com/watch?v=WRKC6SqFGyg

### BPM

100

### Extra Sprites

https://drive.google.com/file/d/1cFMt3B37xzbd3DEtsK0QzoyLFt1xG_6W/view?usp=sharing

**Comment by NAEL2XD** [comment]
Rule 2
