### ISSUE TITLE
Chimamire (B Side Remix) by goobie63 (Original song by Irenic)

### ISSUE THREAD

**Issue by GoobieCheese63** [NAEL2XD/Songs-to-chart-Requests#42]
### Link to the song.

https://youtu.be/u8yVkxd59Ho

### BPM

345

### Extra Sprites

https://drive.google.com/file/d/1Jo5R0OTM3MbPjFXJJMh0tmBvyNgT0V9k/view?usp=sharing sprites were made by NoobusAce, edited by goobie63

**Comment by NAEL2XD** [comment]
*should've added a credits box for this*
Who made the sprites?

**Comment by GoobieCheese63** [comment]
I included it, they were made by noobusace, edited by me (goobie63)

пт, 11 жовт. 2024 р. о 19:24 NAEL2XD ***@***.***> пише:

**Comment by NAEL2XD** [comment]
:+1:

**Comment by NAEL2XD** [comment]
# done

**Comment by GoobieCheese63** [comment]
amazing

пт, 11 жовт. 2024 р. о 22:49 NAEL2XD ***@***.***> пише:
