### ISSUE TITLE
Holy Intrusion

### ISSUE THREAD

**Issue by kasperfnf** [NAEL2XD/Songs-to-chart-Requests#43]
### Link to the song.

https://www.youtube.com/watch?v=FEPo5ivIKvc

### BPM

changes from 153 to 160 (when bambi starts singing)

### Extra Sprites

nothing really

### Credits

Mami sprites and background from the Vs Mami Mod, Bambi sprites from vD&B 3.0

**Comment by NAEL2XD** [comment]
| Chart (normal) | Visuals | Events | Chart (nerfed) |
|--------|--------|--------|--------|
| done | wip | not started |  not started  |

**Comment by NAEL2XD** [comment]
# done
