### ISSUE TITLE
DISTURBANCE (Remade, Bobbby Remix) - Bambi Fantrack

### ISSUE THREAD

**Issue by Miukothoi2011** [NAEL2XD/Songs-to-chart-Requests#6]
### Insert the Song name in the title, then you can paste the link here, optional.

remix by Bobbby
original song by EpicBolSolos
bpm is 290
link: https://youtu.be/JgdGdIHa0i4?si=yx-8KQTf5mxRE163

**Comment by NAEL2XD** [comment]
done
