### ISSUE TITLE
Foreordained

### ISSUE THREAD

**Issue by trademarkman** [NAEL2XD/Songs-to-chart-Requests#8]
### Link to the song.

https://www.youtube.com/watch?v=g39LEER2OY8

### If you know the bpm of the song you've wanna request, input here! Make sure it's in numbers.

i dont know the bpm

**Comment by NAEL2XD** [comment]
1. PLEASE INCLUDE THE COMPOSER!! 
It's litterally right there 
vvvvvvvvvvvvvvvvvvvvv
![image](https://github.com/NAEL2XD/Songs-to-chart-Requests/assets/108278470/acf9aba7-7490-435a-af78-b07357e6f02f)

2. no bpm? technically i could just use tap bpm but it'll probably break the bpm even if it's right

**Comment by NAEL2XD** [comment]
closing this because bpm is invalid (has letters and no numbers)

**Comment by trademarkman** [comment]
😭
