### ISSUE TITLE
Eons

### ISSUE THREAD

**Issue by trademarkman** [NAEL2XD/Songs-to-chart-Requests#9]
### Link to the song.

https://www.youtube.com/watch?v=H5884wPaNCk&t=0s

### If you know the bpm of the song you've wanna request, input here! Make sure it's in numbers.

1e10 BPM LOL (aka 10^10 or 10,000,000,000 / ten billion)

**Comment by NAEL2XD** [comment]
No Base BPM?

**Comment by pixelbackwards1** [comment]
> No Base BPM?

think it's 287 or smth

**Comment by NAEL2XD** [comment]
ok done 👍 will render at night

**Comment by trademarkman** [comment]
> ok done 👍 will render at night

no wonder bro gets no lag 😭
